---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: excercise1
  labels:
    name: excercise1
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchExpressions: 
     - key: activity
       operator: In
       values: 
        - excercise1
        - excercise2
  template:
     metadata:
      labels:
        activity: excercise1
     spec:
      containers:
        - name: IncomaContainer
          image: alpine